# Generated by Django 3.2.16 on 2023-10-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='target_post',
        ),
    ]
