# Generated by Django 3.2.16 on 2023-10-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_target_post_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='publication',
        ),
    ]
