# Generated by Django 3.2.16 on 2023-10-28 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_post_comment_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='publication',
            new_name='post',
        ),
    ]
