# Generated by Django 3.2.16 on 2023-10-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_post_comment_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='publication',
            new_name='post',
        ),
    ]
